### ISSUE TITLE
Github workflow

### ISSUE THREAD

**Issue by qxb3** [HarveyDogs/client-localisation#82]
Does this needs a github workflow to check the translation files syntax?

**Comment by carlislefox** [comment]
Sure I'm open to that, is there a specific action / workflow you have in mind that we could use?

**Comment by qxb3** [comment]
i don't know one but i could make a script in nodejs to do this

**Comment by carlislefox** [comment]
I'm not sure there's any legs to this so I'm closing it if that's alright.

**Comment by qxb3** [comment]
My bad, i completely forgoten about this. i will make the script now😅
